name: FTP Deploy

on:
  push:
    branches:
      - main  # Change to your branch

jobs:
  ftp-deploy:
    name: Deploy Laravel to FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies (local for vendor cache)
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /htdocs/ # <-- yours is direct Laravel in htdocs
          log-level: standard
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
            # **/storage/framework/cache/**
            # **/storage/framework/views/**
          dangerous-clean-slate: false
